### ISSUE TITLE
The sample in 'Design Decisions' encounters an error

### ISSUE THREAD

**Issue by shirakurak** [onyx-lang/onyx-book#2]
First of all, I'm not sure if it's appropriate to open an issue in this repository. I'm very sorry if I'm wrong.

I tried running the sample from [this page](https://docs.onyxlang.io/book/philosophy/design.html#imperative-vs-functional).
（the file is [this](https://github.com/onyx-lang/onyx-book/blob/master/src/philosophy/design.md)）

```onyx
use core {iter, println}

main :: () {
    sequence := i32.[5, 2, 4, 9, 29, 8, 2, 8, 3];

    iter.as_iter(sequence)    // Make the iterator
    |> iter.take(5)           // Only take the first 5 elements
    |> iter.map(x => x * x)   // Square each result

    // Sum the squares with a fold operation
    |> iter.fold(0, (x, y) => x + y)
    |> println()              // Print it to the screen
}
```

At that time, the following error occurred:

```sh
expected token ';', got '}'.
 12 | }
      ^
```

Is there a need for a semicolon at the end of the code?

```
...
  |> println();
...
```

---

```sh
>$ onyx version
> Onyx toolchain version v0.1.8
> Built on Wed Nov 29 01:49:45 2023
> Runtime: wasmer-custom
```

macOS：Sonoma 14.2

**Comment by brendanfh** [comment]
You are absolutely right! There should be a semi-colon in that example. I will get this updated.

Also, this is the perfect place to post issues/errors in the book. I know there are probably many, so I appreciate anyone taking time to point them out!
